FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

ENV WATCHPACK_POLLING=true

CMD ["pnpm", "dev", "--", "-H", "0.0.0.0"]
